details_tabs:
- Offensive:
  - {model: DmgStat, name: Damage}
  - {model: RipStat, name: Rips}
  - {model: MightStat, name: Might}
  - {model: FuryStat, name: Fury}
  - {model: QuickStat, name: Quickness}
  - {model: AlacStat, name: Alacrity}
- Defensive:
  - {model: StabStat, name: Stability}
  - {model: HealStat, name: Healing}
  - {model: BarrierStat, name: Barrier}
  - {model: ProtStat, name: Protection}
  - {model: AegisStat, name: Aegis}
- General:
  - {model: DistStat, name: Distance}
  - {model: DmgTakenStat, name: DmgTaken}
  - {model: SupSpeedStat, name: SuperSpeed}
  - {model: DeathStat, name: Deaths}
  - {model: Summary, name: Summary}
model_list: null
model_names_list: [DmgStat, DistStat, StabStat, CleanseStat, HealStat, RipStat, BarrierStat,
  ProtStat, AegisStat, MightStat, DmgTakenStat, FuryStat, QuickStat, AlacStat, SupSpeedStat,
  DeathStat]
top_page_stats:
- {model: DmgStat, model_name: DmgStat, title: Top Damage, top_limit: 5}
- {model_name: DistStat, title: Top Closest To Tag, top_limit: 5}
- {model_name: StabStat, title: Top Stability, top_limit: 3}
- {model_name: CleanseStat, title: Top Cleanses, top_limit: 3}
- {model_name: HealStat, title: Top Heals, top_limit: 3}
- {model_name: RipStat, title: Top Boonrips, top_limit: 3}
