top_page_stats:
- model_name: DmgStat
  name: Damage
  top_limit: 5
- model_name: DistStat
  name: Sticky
  top_limit: 5
- model_name: StabStat
  name: Stability
  top_limit: 3
- model_name: CleanseStat
  name: Cleanses
  top_limit: 3
- model_name: HealStat
  name: Heals
  top_limit: 3
- model_name: RipStat
  name: Boonrips
  top_limit: 3

model_names_list:
- DmgStat
- DistStat
- StabStat
- CleanseStat
- HealStat
- RipStat
- BarrierStat
- ProtStat
- AegisStat
- MightStat
- DmgTakenStat
- FuryStat
- QuickStat
- AlacStat
- SupSpeedStat
- DeathStat

details_tabs:
- Offensive:
  - name: Damage
    model: DmgStat
  - name: Rips
    model: RipStat
  - name: Might
    model: MightStat
  - name: Fury
    model: FuryStat
  - name: Quickness
    model: QuickStat
  - name: Alacrity
    model: AlacStat
- Defensive:
  - name: Stability
    model: StabStat
  - name: Healing
    model: HealStat
  - name: Barrier
    model: BarrierStat
  - name: Protection
    model: ProtStat
  - name: Aegis
    model: AegisStat
- General:
  - name: Distance
    model: DistStat
  - name: DmgTaken
    model: DmgTakenStat
  - name: SuperSpeed
    model: SupSpeedStat
  - name: Deaths
    model: DeathStat
  - name: Summary
    model: Summary