"""groups

Revision ID: 0eca157f3ee5
Revises: 9d4f190350d3
Create Date: 2022-09-14 11:17:15.504104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eca157f3ee5'
down_revision = '9d4f190350d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_fight_stat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fight_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.Column('boonrips', sa.Integer(), nullable=True),
    sa.Column('cleanses', sa.Integer(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('healing', sa.Integer(), nullable=True),
    sa.Column('distance_to_tag', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('protection', sa.Float(), nullable=True),
    sa.Column('aegis', sa.Float(), nullable=True),
    sa.Column('might', sa.Float(), nullable=True),
    sa.Column('fury', sa.Float(), nullable=True),
    sa.Column('barrier', sa.Integer(), nullable=True),
    sa.Column('dmg_taken', sa.Integer(), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fight_id'], ['fight.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('fight', 'might')
    op.drop_column('fight', 'cleanses')
    op.drop_column('fight', 'stability')
    op.drop_column('fight', 'fury')
    op.drop_column('fight', 'protection')
    op.drop_column('fight', 'damage')
    op.drop_column('fight', 'aegis')
    op.drop_column('fight', 'healing')
    op.drop_column('fight', 'distance_to_tag')
    op.drop_column('fight', 'barrier')
    op.drop_column('fight', 'boonrips')
    op.drop_column('fight', 'deaths')
    op.drop_column('fight', 'dmg_taken')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fight', sa.Column('dmg_taken', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('deaths', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('boonrips', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('barrier', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('distance_to_tag', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('healing', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('aegis', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('damage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('protection', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('fury', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('stability', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('cleanses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('might', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('character_fight_stat')
    # ### end Alembic commands ###
