"""user role management

Revision ID: 15c77e15969f
Revises: 0eca157f3ee5
Create Date: 2022-11-11 08:08:21.423550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c77e15969f'
down_revision = '0eca157f3ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('odin_user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('odin_user', sa.Column('last_checked', sa.Date(), nullable=True))
    op.add_column('odin_user', sa.Column('active', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'odin_user', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'odin_user', type_='foreignkey')
    op.drop_column('odin_user', 'active')
    op.drop_column('odin_user', 'last_checked')
    op.drop_column('odin_user', 'role_id')
    op.drop_table('role')
    # ### end Alembic commands ###
