"""empty message

Revision ID: 2ebd01240e6d
Revises: dae8b37a9740
Create Date: 2022-01-10 07:45:16.124309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebd01240e6d'
down_revision = 'dae8b37a9740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('name_idx', 'profession', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('name_idx', 'profession', type_='unique')
    # ### end Alembic commands ###
