"""empty message

Revision ID: 3156f3c509d6
Revises: e337fcec84be
Create Date: 2022-01-12 09:30:06.394769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3156f3c509d6'
down_revision = 'e337fcec84be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fight', sa.Column('distance_to_tag', sa.Integer(), nullable=True))
    op.add_column('fight', sa.Column('protection', sa.Integer(), nullable=True))
    op.add_column('fight', sa.Column('aegis', sa.Integer(), nullable=True))
    op.add_column('fight', sa.Column('might', sa.Integer(), nullable=True))
    op.add_column('fight', sa.Column('fury', sa.Integer(), nullable=True))
    op.add_column('fight', sa.Column('barrier', sa.Integer(), nullable=True))
    op.add_column('fight', sa.Column('dmg_taken', sa.Integer(), nullable=True))
    op.add_column('fight_summary', sa.Column('skipped', sa.Integer(), nullable=True))
    op.add_column('fight_summary', sa.Column('distance_to_tag', sa.Integer(), nullable=True))
    op.add_column('fight_summary', sa.Column('protection', sa.Integer(), nullable=True))
    op.add_column('fight_summary', sa.Column('aegis', sa.Integer(), nullable=True))
    op.add_column('fight_summary', sa.Column('might', sa.Integer(), nullable=True))
    op.add_column('fight_summary', sa.Column('fury', sa.Integer(), nullable=True))
    op.add_column('fight_summary', sa.Column('barrier', sa.Integer(), nullable=True))
    op.add_column('fight_summary', sa.Column('dmg_taken', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fight_summary', 'dmg_taken')
    op.drop_column('fight_summary', 'barrier')
    op.drop_column('fight_summary', 'fury')
    op.drop_column('fight_summary', 'might')
    op.drop_column('fight_summary', 'aegis')
    op.drop_column('fight_summary', 'protection')
    op.drop_column('fight_summary', 'distance_to_tag')
    op.drop_column('fight_summary', 'skipped')
    op.drop_column('fight', 'dmg_taken')
    op.drop_column('fight', 'barrier')
    op.drop_column('fight', 'fury')
    op.drop_column('fight', 'might')
    op.drop_column('fight', 'aegis')
    op.drop_column('fight', 'protection')
    op.drop_column('fight', 'distance_to_tag')
    # ### end Alembic commands ###
