"""group to rating

Revision ID: 31af5271fcad
Revises: 3a3c581b7d6d
Create Date: 2022-07-13 13:49:54.150632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31af5271fcad'
down_revision = '3a3c581b7d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_fight_rating', sa.Column('group', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_fight_rating', 'group')
    # ### end Alembic commands ###
