"""empty message

Revision ID: 3264c0984e35
Revises: 9768063bb0f0
Create Date: 2022-05-17 14:40:46.838606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3264c0984e35'
down_revision = '9768063bb0f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_date', sa.Date(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_fight_stat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fight_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.Column('boonrips', sa.Integer(), nullable=True),
    sa.Column('cleanses', sa.Integer(), nullable=True),
    sa.Column('stability', sa.Integer(), nullable=True),
    sa.Column('healing', sa.Integer(), nullable=True),
    sa.Column('distance_to_tag', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('protection', sa.Integer(), nullable=True),
    sa.Column('aegis', sa.Integer(), nullable=True),
    sa.Column('might', sa.Integer(), nullable=True),
    sa.Column('fury', sa.Integer(), nullable=True),
    sa.Column('barrier', sa.Integer(), nullable=True),
    sa.Column('dmg_taken', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fight_id'], ['fight.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('fight', 'kills')
    op.drop_column('fight', 'deaths')
    op.drop_column('fight', 'stability')
    op.drop_column('fight', 'might')
    op.drop_column('fight', 'dmg_taken')
    op.drop_column('fight', 'fury')
    op.drop_column('fight', 'damage')
    op.drop_column('fight', 'boonrips')
    op.drop_column('fight', 'distance_to_tag')
    op.drop_column('fight', 'aegis')
    op.drop_column('fight', 'barrier')
    op.drop_column('fight', 'cleanses')
    op.drop_column('fight', 'protection')
    op.drop_column('fight', 'healing')
    op.drop_column('player_stat', 'party')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_stat', sa.Column('party', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('healing', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('protection', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('cleanses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('barrier', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('aegis', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('distance_to_tag', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('boonrips', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('damage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('fury', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('dmg_taken', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('might', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('stability', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('deaths', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight', sa.Column('kills', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('character_fight_stat')
    op.drop_table('log')
    # ### end Alembic commands ###
