"""Added rating

Revision ID: 3a3c581b7d6d
Revises: caf93ed021c5
Create Date: 2022-07-08 14:36:57.455345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a3c581b7d6d'
down_revision = 'caf93ed021c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_fight_rating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fight_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('build_type_id', sa.Integer(), nullable=True),
    sa.Column('damage', sa.Float(), nullable=True),
    sa.Column('boonrips', sa.Float(), nullable=True),
    sa.Column('cleanses', sa.Float(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('healing', sa.Float(), nullable=True),
    sa.Column('distance_to_tag', sa.Float(), nullable=True),
    sa.Column('deaths', sa.Float(), nullable=True),
    sa.Column('protection', sa.Float(), nullable=True),
    sa.Column('aegis', sa.Float(), nullable=True),
    sa.Column('might', sa.Float(), nullable=True),
    sa.Column('fury', sa.Float(), nullable=True),
    sa.Column('barrier', sa.Float(), nullable=True),
    sa.Column('dmg_taken', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['build_type_id'], ['build_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fight_id'], ['fight.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_fight_rating')
    # ### end Alembic commands ###
