"""empty message

Revision ID: 3c4dda5db257
Revises: 7791145dcee8
Create Date: 2022-01-10 11:19:37.702578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4dda5db257'
down_revision = '7791145dcee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'aegis_stat', ['player_stat_id'])
    op.create_unique_constraint(None, 'barrier_stat', ['player_stat_id'])
    op.create_unique_constraint(None, 'cleanse_stat', ['player_stat_id'])
    op.create_unique_constraint(None, 'death_stat', ['player_stat_id'])
    op.create_unique_constraint(None, 'dist_stat', ['player_stat_id'])
    op.create_unique_constraint(None, 'dmg_stat', ['player_stat_id'])
    op.create_unique_constraint(None, 'dmg_taken_stat', ['player_stat_id'])
    op.create_unique_constraint(None, 'fury_stat', ['player_stat_id'])
    op.create_unique_constraint(None, 'heal_stat', ['player_stat_id'])
    op.create_unique_constraint(None, 'kills_stat', ['player_stat_id'])
    op.create_unique_constraint(None, 'might_stat', ['player_stat_id'])
    op.create_unique_constraint(None, 'prot_stat', ['player_stat_id'])
    op.create_unique_constraint(None, 'rip_stat', ['player_stat_id'])
    op.create_unique_constraint(None, 'stab_stat', ['player_stat_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stab_stat', type_='unique')
    op.drop_constraint(None, 'rip_stat', type_='unique')
    op.drop_constraint(None, 'prot_stat', type_='unique')
    op.drop_constraint(None, 'might_stat', type_='unique')
    op.drop_constraint(None, 'kills_stat', type_='unique')
    op.drop_constraint(None, 'heal_stat', type_='unique')
    op.drop_constraint(None, 'fury_stat', type_='unique')
    op.drop_constraint(None, 'dmg_taken_stat', type_='unique')
    op.drop_constraint(None, 'dmg_stat', type_='unique')
    op.drop_constraint(None, 'dist_stat', type_='unique')
    op.drop_constraint(None, 'death_stat', type_='unique')
    op.drop_constraint(None, 'cleanse_stat', type_='unique')
    op.drop_constraint(None, 'barrier_stat', type_='unique')
    op.drop_constraint(None, 'aegis_stat', type_='unique')
    # ### end Alembic commands ###
