"""added alac/quick/supspeed

Revision ID: 3ca276a5aad0
Revises: f46c33decd71
Create Date: 2022-08-17 12:33:12.904507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca276a5aad0'
down_revision = 'f46c33decd71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alac_stat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('times_top', sa.Integer(), nullable=True),
    sa.Column('percentage_top', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('avg_s', sa.Float(), nullable=True),
    sa.Column('player_stat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_stat_id'], ['player_stat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_stat_id')
    )
    op.create_table('quick_stat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('times_top', sa.Integer(), nullable=True),
    sa.Column('percentage_top', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('avg_s', sa.Float(), nullable=True),
    sa.Column('player_stat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_stat_id'], ['player_stat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_stat_id')
    )
    op.create_table('sup_speed_stat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('times_top', sa.Integer(), nullable=True),
    sa.Column('percentage_top', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('avg_s', sa.Float(), nullable=True),
    sa.Column('player_stat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_stat_id'], ['player_stat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_stat_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sup_speed_stat')
    op.drop_table('quick_stat')
    op.drop_table('alac_stat')
    # ### end Alembic commands ###
