"""empty message

Revision ID: 40284a06f4f9
Revises: 2ebd01240e6d
Create Date: 2022-01-10 09:23:25.616925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40284a06f4f9'
down_revision = '2ebd01240e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('raid_character_idx', 'player_stat', ['raid_id', 'character_id'])
    op.create_unique_constraint(None, 'profession', ['abbreviation'])
    op.create_unique_constraint(None, 'raid_type', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raid_type', type_='unique')
    op.drop_constraint(None, 'profession', type_='unique')
    op.drop_constraint('raid_character_idx', 'player_stat', type_='unique')
    # ### end Alembic commands ###
