"""dist

Revision ID: 4dfb9c636e9d
Revises: 7f13652fee45
Create Date: 2022-07-26 09:49:12.793074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dfb9c636e9d'
down_revision = '7f13652fee45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dist_stat', sa.Column('total_dist', sa.Integer(), nullable=True))
    op.add_column('dist_stat', sa.Column('avg_dist_s', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dist_stat', 'avg_dist_s')
    op.drop_column('dist_stat', 'total_dist')
    # ### end Alembic commands ###
