"""empty message

Revision ID: 5970772c98df
Revises: 3264c0984e35
Create Date: 2022-05-17 15:58:45.668604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5970772c98df'
down_revision = '3264c0984e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_fight_stat', sa.Column('group', sa.Integer(), nullable=True))
    op.drop_column('character_fight_stat', 'kills')
    op.add_column('fight', sa.Column('kills', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fight', 'kills')
    op.add_column('character_fight_stat', sa.Column('kills', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('character_fight_stat', 'group')
    # ### end Alembic commands ###
