"""empty message

Revision ID: 6bdc635b6a8e
Revises: 7ce3d930784d
Create Date: 2022-03-03 08:32:06.337618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bdc635b6a8e'
down_revision = '7ce3d930784d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('character', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'character', 'account', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.drop_column('character', 'account_id')
    op.drop_table('account')
    # ### end Alembic commands ###
