"""inheritance

Revision ID: 7f13652fee45
Revises: f33c877d8f14
Create Date: 2022-07-25 15:08:30.705916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f13652fee45'
down_revision = 'f33c877d8f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aegis_stat', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('aegis_stat', sa.Column('avg_s', sa.Float(), nullable=True))
    op.drop_column('aegis_stat', 'avg_aegis_s')
    op.drop_column('aegis_stat', 'total_aegis')
    op.add_column('barrier_stat', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('barrier_stat', sa.Column('avg_s', sa.Float(), nullable=True))
    op.drop_column('barrier_stat', 'total_barrier')
    op.drop_column('barrier_stat', 'avg_barrier_s')
    op.add_column('cleanse_stat', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('cleanse_stat', sa.Column('avg_s', sa.Float(), nullable=True))
    op.drop_column('cleanse_stat', 'total_cleanses')
    op.drop_column('cleanse_stat', 'avg_cleanses_s')
    op.add_column('death_stat', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('death_stat', sa.Column('avg_s', sa.Float(), nullable=True))
    op.drop_column('death_stat', 'total_deaths')
    op.add_column('dist_stat', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('dist_stat', sa.Column('avg_s', sa.Float(), nullable=True))
    op.drop_column('dist_stat', 'avg_dist_s')
    op.drop_column('dist_stat', 'total_dist')
    op.add_column('dmg_stat', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('dmg_stat', sa.Column('avg_s', sa.Float(), nullable=True))
    op.drop_column('dmg_stat', 'total_dmg')
    op.drop_column('dmg_stat', 'avg_dmg_s')
    op.add_column('dmg_taken_stat', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('dmg_taken_stat', sa.Column('avg_s', sa.Float(), nullable=True))
    op.drop_column('dmg_taken_stat', 'avg_dmg_taken_s')
    op.drop_column('dmg_taken_stat', 'total_dmg_taken')
    op.add_column('fury_stat', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('fury_stat', sa.Column('avg_s', sa.Float(), nullable=True))
    op.drop_column('fury_stat', 'total_fury')
    op.drop_column('fury_stat', 'avg_fury_s')
    op.add_column('heal_stat', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('heal_stat', sa.Column('avg_s', sa.Float(), nullable=True))
    op.drop_column('heal_stat', 'avg_heal_s')
    op.drop_column('heal_stat', 'total_heal')
    op.add_column('kills_stat', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('kills_stat', sa.Column('avg_s', sa.Float(), nullable=True))
    op.drop_column('kills_stat', 'total_kills')
    op.add_column('might_stat', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('might_stat', sa.Column('avg_s', sa.Float(), nullable=True))
    op.drop_column('might_stat', 'avg_might_s')
    op.drop_column('might_stat', 'total_might')
    op.add_column('prot_stat', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('prot_stat', sa.Column('avg_s', sa.Float(), nullable=True))
    op.drop_column('prot_stat', 'total_prot')
    op.drop_column('prot_stat', 'avg_prot_s')
    op.add_column('rip_stat', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('rip_stat', sa.Column('avg_s', sa.Float(), nullable=True))
    op.drop_column('rip_stat', 'total_rips')
    op.drop_column('rip_stat', 'avg_rips_s')
    op.add_column('stab_stat', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('stab_stat', sa.Column('avg_s', sa.Float(), nullable=True))
    op.drop_column('stab_stat', 'avg_stab_s')
    op.drop_column('stab_stat', 'total_stab')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stab_stat', sa.Column('total_stab', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stab_stat', sa.Column('avg_stab_s', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('stab_stat', 'avg_s')
    op.drop_column('stab_stat', 'total')
    op.add_column('rip_stat', sa.Column('avg_rips_s', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('rip_stat', sa.Column('total_rips', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('rip_stat', 'avg_s')
    op.drop_column('rip_stat', 'total')
    op.add_column('prot_stat', sa.Column('avg_prot_s', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('prot_stat', sa.Column('total_prot', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('prot_stat', 'avg_s')
    op.drop_column('prot_stat', 'total')
    op.add_column('might_stat', sa.Column('total_might', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('might_stat', sa.Column('avg_might_s', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('might_stat', 'avg_s')
    op.drop_column('might_stat', 'total')
    op.add_column('kills_stat', sa.Column('total_kills', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('kills_stat', 'avg_s')
    op.drop_column('kills_stat', 'total')
    op.add_column('heal_stat', sa.Column('total_heal', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('heal_stat', sa.Column('avg_heal_s', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('heal_stat', 'avg_s')
    op.drop_column('heal_stat', 'total')
    op.add_column('fury_stat', sa.Column('avg_fury_s', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fury_stat', sa.Column('total_fury', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('fury_stat', 'avg_s')
    op.drop_column('fury_stat', 'total')
    op.add_column('dmg_taken_stat', sa.Column('total_dmg_taken', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dmg_taken_stat', sa.Column('avg_dmg_taken_s', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('dmg_taken_stat', 'avg_s')
    op.drop_column('dmg_taken_stat', 'total')
    op.add_column('dmg_stat', sa.Column('avg_dmg_s', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('dmg_stat', sa.Column('total_dmg', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('dmg_stat', 'avg_s')
    op.drop_column('dmg_stat', 'total')
    op.add_column('dist_stat', sa.Column('total_dist', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dist_stat', sa.Column('avg_dist_s', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('dist_stat', 'avg_s')
    op.drop_column('dist_stat', 'total')
    op.add_column('death_stat', sa.Column('total_deaths', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('death_stat', 'avg_s')
    op.drop_column('death_stat', 'total')
    op.add_column('cleanse_stat', sa.Column('avg_cleanses_s', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cleanse_stat', sa.Column('total_cleanses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('cleanse_stat', 'avg_s')
    op.drop_column('cleanse_stat', 'total')
    op.add_column('barrier_stat', sa.Column('avg_barrier_s', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('barrier_stat', sa.Column('total_barrier', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('barrier_stat', 'avg_s')
    op.drop_column('barrier_stat', 'total')
    op.add_column('aegis_stat', sa.Column('total_aegis', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('aegis_stat', sa.Column('avg_aegis_s', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('aegis_stat', 'avg_s')
    op.drop_column('aegis_stat', 'total')
    # ### end Alembic commands ###
