"""empty message

Revision ID: 8cd4f1f7492a
Revises: 6bdc635b6a8e
Create Date: 2022-05-03 13:21:18.345257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8cd4f1f7492a'
down_revision = '6bdc635b6a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.add_column('player_stat', sa.Column('party', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_stat', 'party')
    op.create_table('test',
    sa.Column('Id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('date2', postgresql.TIME(timezone=True), autoincrement=False, nullable=True),
    sa.Column('date3', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('date4', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='test_pkey')
    )
    # ### end Alembic commands ###
