"""empty message

Revision ID: 8e90d8f7109c
Revises: 3156f3c509d6
Create Date: 2022-01-17 15:11:22.737519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e90d8f7109c'
down_revision = '3156f3c509d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fight_summary', sa.Column('start_time', sa.String(), nullable=True))
    op.add_column('fight_summary', sa.Column('end_time', sa.String(), nullable=True))
    op.alter_column('fight_summary', 'avg_allies',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('fight_summary', 'avg_enemies',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fight_summary', 'avg_enemies',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fight_summary', 'avg_allies',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('fight_summary', 'end_time')
    op.drop_column('fight_summary', 'start_time')
    # ### end Alembic commands ###
