"""empty message

Revision ID: 9768063bb0f0
Revises: 896e287ba12c
Create Date: 2022-05-12 07:59:10.373409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9768063bb0f0'
down_revision = '896e287ba12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('log_account_id_fkey', 'log', type_='foreignkey')
    op.create_foreign_key(None, 'log', 'account', ['account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.create_foreign_key('log_account_id_fkey', 'log', 'raid', ['account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
