"""added stats to raid summary

Revision ID: 9d4f190350d3
Revises: 3ca276a5aad0
Create Date: 2022-08-30 13:51:41.304703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4f190350d3'
down_revision = '3ca276a5aad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fight_summary', sa.Column('quickness', sa.Float(), nullable=True))
    op.add_column('fight_summary', sa.Column('alacrity', sa.Float(), nullable=True))
    op.add_column('fight_summary', sa.Column('superspeed', sa.Float(), nullable=True))
    op.alter_column('fight_summary', 'stability',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('fight_summary', 'protection',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('fight_summary', 'aegis',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('fight_summary', 'might',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('fight_summary', 'fury',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fight_summary', 'fury',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fight_summary', 'might',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fight_summary', 'aegis',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fight_summary', 'protection',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fight_summary', 'stability',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('fight_summary', 'superspeed')
    op.drop_column('fight_summary', 'alacrity')
    op.drop_column('fight_summary', 'quickness')
    # ### end Alembic commands ###
