"""empty message

Revision ID: a1ac98a2f68b
Revises: bb7ffa5a0be8
Create Date: 2023-05-07 15:17:47.398102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ac98a2f68b'
down_revision = 'bb7ffa5a0be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dmg_other_stat',
    sa.Column('player_stat_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('times_top', sa.Integer(), nullable=True),
    sa.Column('percentage_top', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('avg_s', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_stat_id'], ['player_stat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_stat_id')
    )
    op.create_table('dmg_players_stat',
    sa.Column('player_stat_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('times_top', sa.Integer(), nullable=True),
    sa.Column('percentage_top', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('avg_s', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_stat_id'], ['player_stat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_stat_id')
    )
    op.create_table('heal_other_stat',
    sa.Column('player_stat_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('times_top', sa.Integer(), nullable=True),
    sa.Column('percentage_top', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('avg_s', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_stat_id'], ['player_stat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_stat_id')
    )
    op.create_table('heal_players_stat',
    sa.Column('player_stat_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('times_top', sa.Integer(), nullable=True),
    sa.Column('percentage_top', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('avg_s', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_stat_id'], ['player_stat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_stat_id')
    )
    with op.batch_alter_table('character_fight_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('damage_players', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('damage_other', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('healing_players', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('healing_other', sa.Float(), nullable=True))

    with op.batch_alter_table('character_fight_stat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('damage_players', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('damage_other', sa.Integer(), nullable=True))

    with op.batch_alter_table('fight_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('damage_players', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('damage_other', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('healing_players', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('healing_other', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fight_summary', schema=None) as batch_op:
        batch_op.drop_column('healing_other')
        batch_op.drop_column('healing_players')
        batch_op.drop_column('damage_other')
        batch_op.drop_column('damage_players')

    with op.batch_alter_table('character_fight_stat', schema=None) as batch_op:
        batch_op.drop_column('damage_other')
        batch_op.drop_column('damage_players')

    with op.batch_alter_table('character_fight_rating', schema=None) as batch_op:
        batch_op.drop_column('healing_other')
        batch_op.drop_column('healing_players')
        batch_op.drop_column('damage_other')
        batch_op.drop_column('damage_players')

    op.drop_table('heal_players_stat')
    op.drop_table('heal_other_stat')
    op.drop_table('dmg_players_stat')
    op.drop_table('dmg_other_stat')
    # ### end Alembic commands ###
