"""empty message

Revision ID: b9594f56e250
Revises: e671df580ed3
Create Date: 2022-01-11 10:14:14.122076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9594f56e250'
down_revision = 'e671df580ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fight_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raid_id', sa.Integer(), nullable=True),
    sa.Column('fight_date', sa.Date(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('avg_allies', sa.Integer(), nullable=True),
    sa.Column('avg_enemies', sa.Integer(), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.Column('boonrips', sa.Integer(), nullable=True),
    sa.Column('cleanses', sa.Integer(), nullable=True),
    sa.Column('stability', sa.Integer(), nullable=True),
    sa.Column('healing', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['raid_id'], ['raid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fight_summary')
    # ### end Alembic commands ###
