"""empty message

Revision ID: bb7ffa5a0be8
Revises: 31af5271fcad
Create Date: 2023-03-22 21:29:58.402847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7ffa5a0be8'
down_revision = '31af5271fcad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripped_stat',
    sa.Column('player_stat_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('times_top', sa.Integer(), nullable=True),
    sa.Column('percentage_top', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('avg_s', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_stat_id'], ['player_stat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_stat_id')
    )
    with op.batch_alter_table('character_fight_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripped', sa.Float(), nullable=True))

    with op.batch_alter_table('character_fight_stat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripped', sa.Integer(), nullable=True))

    with op.batch_alter_table('fight_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripped', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fight_summary', schema=None) as batch_op:
        batch_op.drop_column('stripped')

    with op.batch_alter_table('character_fight_stat', schema=None) as batch_op:
        batch_op.drop_column('stripped')

    with op.batch_alter_table('character_fight_rating', schema=None) as batch_op:
        batch_op.drop_column('stripped')

    op.drop_table('stripped_stat')
    # ### end Alembic commands ###
