"""build_type

Revision ID: caf93ed021c5
Revises: 4049d54bf5a3
Create Date: 2022-07-07 09:07:12.106430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf93ed021c5'
down_revision = '4049d54bf5a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('character_fight_stat', sa.Column('build_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'character_fight_stat', 'build_type', ['build_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'character_fight_stat', type_='foreignkey')
    op.drop_column('character_fight_stat', 'build_type_id')
    op.drop_table('build_type')
    # ### end Alembic commands ###
