"""empty message

Revision ID: cbad42daec0d
Revises: 3c4dda5db257
Create Date: 2022-01-10 13:18:37.348773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbad42daec0d'
down_revision = '3c4dda5db257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raid', sa.Column('raid_type_id', sa.Integer(), nullable=True))
    op.drop_constraint('raid_raid_type_fkey', 'raid', type_='foreignkey')
    op.create_foreign_key(None, 'raid', 'raid_type', ['raid_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('raid', 'raid_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raid', sa.Column('raid_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'raid', type_='foreignkey')
    op.create_foreign_key('raid_raid_type_fkey', 'raid', 'raid_type', ['raid_type'], ['id'], ondelete='CASCADE')
    op.drop_column('raid', 'raid_type_id')
    # ### end Alembic commands ###
