"""empty message

Revision ID: dae8b37a9740
Revises: 18c4ff4cb476
Create Date: 2022-01-08 15:32:33.899180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae8b37a9740'
down_revision = '18c4ff4cb476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profession', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profession', 'color')
    # ### end Alembic commands ###
