"""empty message

Revision ID: e671df580ed3
Revises: cbad42daec0d
Create Date: 2022-01-10 15:26:43.543040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e671df580ed3'
down_revision = 'cbad42daec0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aegis_stat', sa.Column('percentage_top', sa.Integer(), nullable=True))
    op.add_column('barrier_stat', sa.Column('percentage_top', sa.Integer(), nullable=True))
    op.add_column('cleanse_stat', sa.Column('percentage_top', sa.Integer(), nullable=True))
    op.add_column('death_stat', sa.Column('percentage_top', sa.Integer(), nullable=True))
    op.add_column('dist_stat', sa.Column('percentage_top', sa.Integer(), nullable=True))
    op.add_column('dmg_stat', sa.Column('percentage_top', sa.Integer(), nullable=True))
    op.add_column('dmg_taken_stat', sa.Column('percentage_top', sa.Integer(), nullable=True))
    op.add_column('fury_stat', sa.Column('percentage_top', sa.Integer(), nullable=True))
    op.add_column('heal_stat', sa.Column('percentage_top', sa.Integer(), nullable=True))
    op.add_column('kills_stat', sa.Column('percentage_top', sa.Integer(), nullable=True))
    op.add_column('might_stat', sa.Column('percentage_top', sa.Integer(), nullable=True))
    op.add_column('prot_stat', sa.Column('percentage_top', sa.Integer(), nullable=True))
    op.add_column('rip_stat', sa.Column('percentage_top', sa.Integer(), nullable=True))
    op.add_column('stab_stat', sa.Column('percentage_top', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stab_stat', 'percentage_top')
    op.drop_column('rip_stat', 'percentage_top')
    op.drop_column('prot_stat', 'percentage_top')
    op.drop_column('might_stat', 'percentage_top')
    op.drop_column('kills_stat', 'percentage_top')
    op.drop_column('heal_stat', 'percentage_top')
    op.drop_column('fury_stat', 'percentage_top')
    op.drop_column('dmg_taken_stat', 'percentage_top')
    op.drop_column('dmg_stat', 'percentage_top')
    op.drop_column('dist_stat', 'percentage_top')
    op.drop_column('death_stat', 'percentage_top')
    op.drop_column('cleanse_stat', 'percentage_top')
    op.drop_column('barrier_stat', 'percentage_top')
    op.drop_column('aegis_stat', 'percentage_top')
    # ### end Alembic commands ###
