"""empty message

Revision ID: e9845885b4b7
Revises: a1ac98a2f68b
Create Date: 2023-05-07 15:29:41.811794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9845885b4b7'
down_revision = 'a1ac98a2f68b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_fight_stat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('healing_players', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('healing_other', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_fight_stat', schema=None) as batch_op:
        batch_op.drop_column('healing_other')
        batch_op.drop_column('healing_players')

    # ### end Alembic commands ###
