"""power to role

Revision ID: f02df06587d2
Revises: 15c77e15969f
Create Date: 2022-11-29 15:00:59.635291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02df06587d2'
down_revision = '15c77e15969f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('power', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'power')
    # ### end Alembic commands ###
