"""Added guild table

Revision ID: f33c877d8f14
Revises: 9768063bb0f0
Create Date: 2022-05-25 11:14:43.311300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33c877d8f14'
down_revision = '9768063bb0f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('api_id', sa.String(), nullable=True),
    sa.Column('leader_key', sa.String(), nullable=True),
    sa.Column('members_updated_last', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('account', sa.Column('guild_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'account', 'guild', ['guild_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'guild_id')
    op.drop_table('guild')
    # ### end Alembic commands ###
